replicaCount: 4

image:
  repository: tehnogen/neoflex
  tag: latest

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 32668

deployment:
  name: my-neoflex-helm
  labels:
    app: my-neoflex-helm
